import axios from "axios";

export async function createEnergy(
  year,
  company,
  consumedElectricityBought,
  naturalGasBought,
  dieselBought,
  fuelOilBought,
  nuclearBought,
  coalBought,
  windEnergyBought,
  hidrelectricBought,
  solarBought,
  biomassBought,
  biogasBought,
  solidWasteIncinerationBought,
  consumedElectricityProduced,
  hidrelectricProduced,
  solarProduced,
  biomassProduced,
  biogasProduced,
  surplusEntered,
  pureDieselUsedInCompany,
  pureGasolineUsedInCompany,
  biofuelUsedInCompany,
  lubricantUsedInCompany,
  butaneUsedInCompany,
  propaneUsedInCompany,
  gplAutoUsedInCompany,
  naturalGasUsedInCompany,
  biogasUsedInCompany,
  woodUsedInCompany,
  pelletsUsedInCompany
) {
  return await axios.post(
    `http://localhost:5000/api/users/createEnergy`,
    {
      year: year,
      company_name: company,
      consumed_electricity_bought: consumedElectricityBought,
      natural_gas_bought: naturalGasBought,
      diesel_bought: dieselBought,
      fuel_oil_bought: fuelOilBought,
      nuclear_bought: nuclearBought,
      coal_bought: coalBought,
      wind_energy_bought: windEnergyBought,
      hidrelectric_bought: hidrelectricBought,
      solar_bought: solarBought,
      biomass_bought: biomassBought,
      biogas_bought: biogasBought,
      solid_waste_incineration_bought: solidWasteIncinerationBought,
      consumed_electricity_produced: consumedElectricityProduced,
      hidrelectric_produced: hidrelectricProduced,
      solar_produced: solarProduced,
      biomass_produced: biomassProduced,
      biogas_produced: biogasProduced,
      surplus_entered: surplusEntered,
      pure_diesel_used_in_company: pureDieselUsedInCompany,
      pure_gasoline_used_in_company: pureGasolineUsedInCompany,
      biofuel_used_in_company: biofuelUsedInCompany,
      lubricant_used_in_company: lubricantUsedInCompany,
      butane_used_in_company: butaneUsedInCompany,
      propane_used_in_company: propaneUsedInCompany,
      gpl_auto_used_in_company: gplAutoUsedInCompany,
      natural_gas_used_in_company: naturalGasUsedInCompany,
      biogas_used_in_company: biogasUsedInCompany,
      wood_used_in_company: woodUsedInCompany,
      pellets_used_in_company: pelletsUsedInCompany,
    },
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
}

export async function getEnergyByYearAndCompany(year, company) {
  return await axios.get(
    "http://localhost:5000/api/users/getEnergyByYearAndCompany",
    {
      params: { year: year, company_name: company },
    }
  );
}

export async function updateEnergy(
  year,
  company,
  consumedElectricityBought,
  naturalGasBought,
  dieselBought,
  fuelOilBought,
  nuclearBought,
  coalBought,
  windEnergyBought,
  hidrelectricBought,
  solarBought,
  biomassBought,
  biogasBought,
  solidWasteIncinerationBought,
  consumedElectricityProduced,
  hidrelectricProduced,
  solarProduced,
  biomassProduced,
  biogasProduced,
  surplusEntered,
  pureDieselUsedInCompany,
  pureGasolineUsedInCompany,
  biofuelUsedInCompany,
  lubricantUsedInCompany,
  butaneUsedInCompany,
  propaneUsedInCompany,
  gplAutoUsedInCompany,
  naturalGasUsedInCompany,
  biogasUsedInCompany,
  woodUsedInCompany,
  pelletsUsedInCompany
) {
  return await axios.put(
    `http://localhost:5000/api/users/updateEnergy/${year}/${company}`,
    {
      consumed_electricity_bought: consumedElectricityBought,
      natural_gas_bought: naturalGasBought,
      diesel_bought: dieselBought,
      fuel_oil_bought: fuelOilBought,
      nuclear_bought: nuclearBought,
      coal_bought: coalBought,
      wind_energy_bought: windEnergyBought,
      hidrelectric_bought: hidrelectricBought,
      solar_bought: solarBought,
      biomass_bought: biomassBought,
      biogas_bought: biogasBought,
      solid_waste_incineration_bought: solidWasteIncinerationBought,
      consumed_electricity_produced: consumedElectricityProduced,
      hidrelectric_produced: hidrelectricProduced,
      solar_produced: solarProduced,
      biomass_produced: biomassProduced,
      biogas_produced: biogasProduced,
      surplus_entered: surplusEntered,
      pure_diesel_used_in_company: pureDieselUsedInCompany,
      pure_gasoline_used_in_company: pureGasolineUsedInCompany,
      biofuel_used_in_company: biofuelUsedInCompany,
      lubricant_used_in_company: lubricantUsedInCompany,
      butane_used_in_company: butaneUsedInCompany,
      propane_used_in_company: propaneUsedInCompany,
      gpl_auto_used_in_company: gplAutoUsedInCompany,
      natural_gas_used_in_company: naturalGasUsedInCompany,
      biogas_used_in_company: biogasUsedInCompany,
      wood_used_in_company: woodUsedInCompany,
      pellets_used_in_company: pelletsUsedInCompany,
    },
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
}
