import axios from "axios";

export async function createWater(
  year,
  company,
  totalWaterFromNetwork,
  totalWaterFromWell,
  totalWaterFromCistern,
  totalWaterReused,
  waterConsumedByEquipmentCleaningOnPressing,
  numberOfCleaningPerMonthOnPressing,
  waterConsumedByEquipmentCleaningOnTrasfega,
  numberOfCleaningPerMonthOnTrasfega,
  waterConsumedByEquipmentCleaningOnEstabilization,
  numberOfCleaningPerMonthOnEstabilization,
  waterConsumedByEquipmentCleaningOnFiltration,
  numberOfCleaningPerMonthOnFiltration,
  waterConsumedByEquipmentCleaningOnDifferentFloors,
  numberOfCleaningPerMonthOnDifferentFloors,
  waterConsumedByEquipmentCleaningOnSterilization,
  numberOfCleaningPerMonthOnSterilization,
  waterConsumedByEquipmentCleaningOnFilling,
  numberOfCleaningPerMonthOnFilling,
  waterConsumedByEquipmentCleaningOnLabeling,
  numberOfCleaningPerMonthOnLabeling,
  waterConsumedByEquipmentCleaningOnBottlingDifferentFloors,
  numberOfCleaningPerMonthOnBottlingDifferentFloors,
  phHighSeasonGeneratedWater,
  phLowSeasonGeneratedWater,
  conductivityHighSeasonGeneratedWater,
  conductivityLowSeasonGeneratedWater,
  turbidityHighSeasonGeneratedWater,
  turbidityLowSeasonGeneratedWater,
  CQOHighSeasonGeneratedWater,
  CQOLowSeasonGeneratedWater,
  CBOHighSeasonGeneratedWater,
  CBOLowSeasonGeneratedWater,
  SSTHighSeasonGeneratedWater,
  SSTLowSeasonGeneratedWater,
  NTKHighSeasonGeneratedWater,
  NTKLowSeasonGeneratedWater,
  fenoisHighSeasonGeneratedWater,
  fenoisLowSeasonGeneratedWater,
  fosforoHighSeasonGeneratedWater,
  fosforoLowSeasonGeneratedWater,
  nitratosHighSeasonGeneratedWater,
  nitratosLowSeasonGeneratedWater,
  sulfatosHighSeasonGeneratedWater,
  sulfatosLowSeasonGeneratedWater,
  ferroHighSeasonGeneratedWater,
  ferroLowSeasonGeneratedWater,
  aluminumHighSeasonGeneratedWater,
  aluminumLowSeasonGeneratedWater,
  cadmioHighSeasonGeneratedWater,
  cadmioLowSeasonGeneratedWater,
  cobreHighSeasonGeneratedWater,
  cobreLowSeasonGeneratedWater,
  cromioHighSeasonGeneratedWater,
  cromioLowSeasonGeneratedWater,
  manganesHighSeasonGeneratedWater,
  manganesLowSeasonGeneratedWater,
  phHighSeasonTreatedWater,
  phLowSeasonTreatedWater,
  conductivityHighSeasonTreatedWater,
  conductivityLowSeasonTreatedWater,
  turbidityHighSeasonTreatedWater,
  turbidityLowSeasonTreatedWater,
  CQOHighSeasonTreatedWater,
  CQOLowSeasonTreatedWater,
  CBOHighSeasonTreatedWater,
  CBOLowSeasonTreatedWater,
  SSTHighSeasonTreatedWater,
  SSTLowSeasonTreatedWater,
  NTKHighSeasonTreatedWater,
  NTKLowSeasonTreatedWater,
  fenoisHighSeasonTreatedWater,
  fenoisLowSeasonTreatedWater,
  fosforoHighSeasonTreatedWater,
  fosforoLowSeasonTreatedWater,
  nitratosHighSeasonTreatedWater,
  nitratosLowSeasonTreatedWater,
  sulfatosHighSeasonTreatedWater,
  sulfatosLowSeasonTreatedWater,
  ferroHighSeasonTreatedWater,
  ferroLowSeasonTreatedWater,
  aluminumHighSeasonTreatedWater,
  aluminumLowSeasonTreatedWater,
  cadmioHighSeasonTreatedWater,
  cadmioLowSeasonTreatedWater,
  cobreHighSeasonTreatedWater,
  cobreLowSeasonTreatedWater,
  cromioHighSeasonTreatedWater,
  cromioLowSeasonTreatedWater,
  manganesHighSeasonTreatedWater,
  manganesLowSeasonTreatedWater
) {
  return await axios.post(
    `http://localhost:5000/api/users/createWater`,
    {
      year: year,
      company_name: company,
      total_water_from_network: totalWaterFromNetwork,
      total_water_from_well: totalWaterFromWell,
      total_water_from_cistern: totalWaterFromCistern,
      total_water_reused: totalWaterReused,
      water_consumed_by_equipment_cleaning_on_pressing:
        waterConsumedByEquipmentCleaningOnPressing,
      number_of_cleaning_per_month_on_pressing:
        numberOfCleaningPerMonthOnPressing,
      water_consumed_by_equipment_cleaning_on_trasfega:
        waterConsumedByEquipmentCleaningOnTrasfega,
      number_of_cleaning_per_month_on_trasfega:
        numberOfCleaningPerMonthOnTrasfega,
      water_consumed_by_equipment_cleaning_on_estabilization:
        waterConsumedByEquipmentCleaningOnEstabilization,
      number_of_cleaning_per_month_on_estabilization:
        numberOfCleaningPerMonthOnEstabilization,
      water_consumed_by_equipment_cleaning_on_filtration:
        waterConsumedByEquipmentCleaningOnFiltration,
      number_of_cleaning_per_month_on_filtration:
        numberOfCleaningPerMonthOnFiltration,
      water_consumed_by_equipment_cleaning_on_different_floors:
        waterConsumedByEquipmentCleaningOnDifferentFloors,
      number_of_cleaning_per_month_on_different_floors:
        numberOfCleaningPerMonthOnDifferentFloors,
      water_consumed_by_equipment_cleaning_on_sterilization:
        waterConsumedByEquipmentCleaningOnSterilization,
      number_of_cleaning_per_month_on_sterilization:
        numberOfCleaningPerMonthOnSterilization,
      water_consumed_by_equipment_cleaning_on_filling:
        waterConsumedByEquipmentCleaningOnFilling,
      number_of_cleaning_per_month_on_filling:
        numberOfCleaningPerMonthOnFilling,
      water_consumed_by_equipment_cleaning_on_labeling:
        waterConsumedByEquipmentCleaningOnLabeling,
      number_of_cleaning_per_month_on_labeling:
        numberOfCleaningPerMonthOnLabeling,
      water_consumed_by_equipment_cleaning_on_bottling_different_floors:
        waterConsumedByEquipmentCleaningOnBottlingDifferentFloors,
      number_of_cleaning_per_month_on_bottling_different_floors:
        numberOfCleaningPerMonthOnBottlingDifferentFloors,
      ph_high_season_generated_water: phHighSeasonGeneratedWater,
      ph_low_season_generated_water: phLowSeasonGeneratedWater,
      conductivity_high_season_generated_water:
        conductivityHighSeasonGeneratedWater,
      conductivity_low_season_generated_water:
        conductivityLowSeasonGeneratedWater,
      turbidity_high_season_generated_water: turbidityHighSeasonGeneratedWater,
      turbidity_low_season_generated_water: turbidityLowSeasonGeneratedWater,
      CQO_high_season_generated_water: CQOHighSeasonGeneratedWater,
      CQO_low_season_generated_water: CQOLowSeasonGeneratedWater,
      CBO_high_season_generated_water: CBOHighSeasonGeneratedWater,
      CBO_low_season_generated_water: CBOLowSeasonGeneratedWater,
      SST_high_season_generated_water: SSTHighSeasonGeneratedWater,
      SST_low_season_generated_water: SSTLowSeasonGeneratedWater,
      NTK_high_season_generated_water: NTKHighSeasonGeneratedWater,
      NTK_low_season_generated_water: NTKLowSeasonGeneratedWater,
      fenois_high_season_generated_water: fenoisHighSeasonGeneratedWater,
      fenois_low_season_generated_water: fenoisLowSeasonGeneratedWater,
      fosforo_high_season_generated_water: fosforoHighSeasonGeneratedWater,
      fosforo_low_season_generated_water: fosforoLowSeasonGeneratedWater,
      nitratos_high_season_generated_water: nitratosHighSeasonGeneratedWater,
      nitratos_low_season_generated_water: nitratosLowSeasonGeneratedWater,
      sulfatos_high_season_generated_water: sulfatosHighSeasonGeneratedWater,
      sulfatos_low_season_generated_water: sulfatosLowSeasonGeneratedWater,
      ferro_high_season_generated_water: ferroHighSeasonGeneratedWater,
      ferro_low_season_generated_water: ferroLowSeasonGeneratedWater,
      aluminum_high_season_generated_water: aluminumHighSeasonGeneratedWater,
      aluminum_low_season_generated_water: aluminumLowSeasonGeneratedWater,
      cadmio_high_season_generated_water: cadmioHighSeasonGeneratedWater,
      cadmio_low_season_generated_water: cadmioLowSeasonGeneratedWater,
      cobre_high_season_generated_water: cobreHighSeasonGeneratedWater,
      cobre_low_season_generated_water: cobreLowSeasonGeneratedWater,
      cromio_high_season_generated_water: cromioHighSeasonGeneratedWater,
      cromio_low_season_generated_water: cromioLowSeasonGeneratedWater,
      manganes_high_season_generated_water: manganesHighSeasonGeneratedWater,
      manganes_low_season_generated_water: manganesLowSeasonGeneratedWater,
      ph_high_season_treated_water: phHighSeasonTreatedWater,
      ph_low_season_treated_water: phLowSeasonTreatedWater,
      conductivity_high_season_treated_water:
        conductivityHighSeasonTreatedWater,
      conductivity_low_season_treated_water: conductivityLowSeasonTreatedWater,
      turbidity_high_season_treated_water: turbidityHighSeasonTreatedWater,
      turbidity_low_season_treated_water: turbidityLowSeasonTreatedWater,
      CQO_high_season_treated_water: CQOHighSeasonTreatedWater,
      CQO_low_season_treated_water: CQOLowSeasonTreatedWater,
      CBO_high_season_treated_water: CBOHighSeasonTreatedWater,
      CBO_low_season_treated_water: CBOLowSeasonTreatedWater,
      SST_high_season_treated_water: SSTHighSeasonTreatedWater,
      SST_low_season_treated_water: SSTLowSeasonTreatedWater,
      NTK_high_season_treated_water: NTKHighSeasonTreatedWater,
      NTK_low_season_treated_water: NTKLowSeasonTreatedWater,
      fenois_high_season_treated_water: fenoisHighSeasonTreatedWater,
      fenois_low_season_treated_water: fenoisLowSeasonTreatedWater,
      fosforo_high_season_treated_water: fosforoHighSeasonTreatedWater,
      fosforo_low_season_treated_water: fosforoLowSeasonTreatedWater,
      nitratos_high_season_treated_water: nitratosHighSeasonTreatedWater,
      nitratos_low_season_treated_water: nitratosLowSeasonTreatedWater,
      sulfatos_high_season_treated_water: sulfatosHighSeasonTreatedWater,
      sulfatos_low_season_treated_water: sulfatosLowSeasonTreatedWater,
      ferro_high_season_treated_water: ferroHighSeasonTreatedWater,
      ferro_low_season_treated_water: ferroLowSeasonTreatedWater,
      aluminum_high_season_treated_water: aluminumHighSeasonTreatedWater,
      aluminum_low_season_treated_water: aluminumLowSeasonTreatedWater,
      cadmio_high_season_treated_water: cadmioHighSeasonTreatedWater,
      cadmio_low_season_treated_water: cadmioLowSeasonTreatedWater,
      cobre_high_season_treated_water: cobreHighSeasonTreatedWater,
      cobre_low_season_treated_water: cobreLowSeasonTreatedWater,
      cromio_high_season_treated_water: cromioHighSeasonTreatedWater,
      cromio_low_season_treated_water: cromioLowSeasonTreatedWater,
      manganes_high_season_treated_water: manganesHighSeasonTreatedWater,
      manganes_low_season_treated_water: manganesLowSeasonTreatedWater,
    },
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
}

export async function getWaterByYearAndCompany(year, company) {
  return await axios.get(
    "http://localhost:5000/api/users/getWaterByYearAndCompany",
    {
      params: { year: year, company_name: company },
    }
  );
}

export async function updateWater(
  year,
  company,
  totalWaterFromNetwork,
  totalWaterFromWell,
  totalWaterFromCistern,
  totalWaterReused,
  waterConsumedByEquipmentCleaningOnPressing,
  numberOfCleaningPerMonthOnPressing,
  waterConsumedByEquipmentCleaningOnTrasfega,
  numberOfCleaningPerMonthOnTrasfega,
  waterConsumedByEquipmentCleaningOnEstabilization,
  numberOfCleaningPerMonthOnEstabilization,
  waterConsumedByEquipmentCleaningOnFiltration,
  numberOfCleaningPerMonthOnFiltration,
  waterConsumedByEquipmentCleaningOnDifferentFloors,
  numberOfCleaningPerMonthOnDifferentFloors,
  waterConsumedByEquipmentCleaningOnSterilization,
  numberOfCleaningPerMonthOnSterilization,
  waterConsumedByEquipmentCleaningOnFilling,
  numberOfCleaningPerMonthOnFilling,
  waterConsumedByEquipmentCleaningOnLabeling,
  numberOfCleaningPerMonthOnLabeling,
  waterConsumedByEquipmentCleaningOnBottlingDifferentFloors,
  numberOfCleaningPerMonthOnBottlingDifferentFloors,
  phHighSeasonGeneratedWater,
  phLowSeasonGeneratedWater,
  conductivityHighSeasonGeneratedWater,
  conductivityLowSeasonGeneratedWater,
  turbidityHighSeasonGeneratedWater,
  turbidityLowSeasonGeneratedWater,
  CQOHighSeasonGeneratedWater,
  CQOLowSeasonGeneratedWater,
  CBOHighSeasonGeneratedWater,
  CBOLowSeasonGeneratedWater,
  SSTHighSeasonGeneratedWater,
  SSTLowSeasonGeneratedWater,
  NTKHighSeasonGeneratedWater,
  NTKLowSeasonGeneratedWater,
  fenoisHighSeasonGeneratedWater,
  fenoisLowSeasonGeneratedWater,
  fosforoHighSeasonGeneratedWater,
  fosforoLowSeasonGeneratedWater,
  nitratosHighSeasonGeneratedWater,
  nitratosLowSeasonGeneratedWater,
  sulfatosHighSeasonGeneratedWater,
  sulfatosLowSeasonGeneratedWater,
  ferroHighSeasonGeneratedWater,
  ferroLowSeasonGeneratedWater,
  aluminumHighSeasonGeneratedWater,
  aluminumLowSeasonGeneratedWater,
  cadmioHighSeasonGeneratedWater,
  cadmioLowSeasonGeneratedWater,
  cobreHighSeasonGeneratedWater,
  cobreLowSeasonGeneratedWater,
  cromioHighSeasonGeneratedWater,
  cromioLowSeasonGeneratedWater,
  manganesHighSeasonGeneratedWater,
  manganesLowSeasonGeneratedWater,
  phHighSeasonTreatedWater,
  phLowSeasonTreatedWater,
  conductivityHighSeasonTreatedWater,
  conductivityLowSeasonTreatedWater,
  turbidityHighSeasonTreatedWater,
  turbidityLowSeasonTreatedWater,
  CQOHighSeasonTreatedWater,
  CQOLowSeasonTreatedWater,
  CBOHighSeasonTreatedWater,
  CBOLowSeasonTreatedWater,
  SSTHighSeasonTreatedWater,
  SSTLowSeasonTreatedWater,
  NTKHighSeasonTreatedWater,
  NTKLowSeasonTreatedWater,
  fenoisHighSeasonTreatedWater,
  fenoisLowSeasonTreatedWater,
  fosforoHighSeasonTreatedWater,
  fosforoLowSeasonTreatedWater,
  nitratosHighSeasonTreatedWater,
  nitratosLowSeasonTreatedWater,
  sulfatosHighSeasonTreatedWater,
  sulfatosLowSeasonTreatedWater,
  ferroHighSeasonTreatedWater,
  ferroLowSeasonTreatedWater,
  aluminumHighSeasonTreatedWater,
  aluminumLowSeasonTreatedWater,
  cadmioHighSeasonTreatedWater,
  cadmioLowSeasonTreatedWater,
  cobreHighSeasonTreatedWater,
  cobreLowSeasonTreatedWater,
  cromioHighSeasonTreatedWater,
  cromioLowSeasonTreatedWater,
  manganesHighSeasonTreatedWater,
  manganesLowSeasonTreatedWater
) {
  return await axios.put(
    `http://localhost:5000/api/users/updateWater/${year}/${company}`,
    {
      total_water_from_network: totalWaterFromNetwork,
      total_water_from_well: totalWaterFromWell,
      total_water_from_cistern: totalWaterFromCistern,
      total_water_reused: totalWaterReused,
      water_consumed_by_equipment_cleaning_on_pressing:
        waterConsumedByEquipmentCleaningOnPressing,
      number_of_cleaning_per_month_on_pressing:
        numberOfCleaningPerMonthOnPressing,
      water_consumed_by_equipment_cleaning_on_trasfega:
        waterConsumedByEquipmentCleaningOnTrasfega,
      number_of_cleaning_per_month_on_trasfega:
        numberOfCleaningPerMonthOnTrasfega,
      water_consumed_by_equipment_cleaning_on_estabilization:
        waterConsumedByEquipmentCleaningOnEstabilization,
      number_of_cleaning_per_month_on_estabilization:
        numberOfCleaningPerMonthOnEstabilization,
      water_consumed_by_equipment_cleaning_on_filtration:
        waterConsumedByEquipmentCleaningOnFiltration,
      number_of_cleaning_per_month_on_filtration:
        numberOfCleaningPerMonthOnFiltration,
      water_consumed_by_equipment_cleaning_on_different_floors:
        waterConsumedByEquipmentCleaningOnDifferentFloors,
      number_of_cleaning_per_month_on_different_floors:
        numberOfCleaningPerMonthOnDifferentFloors,
      water_consumed_by_equipment_cleaning_on_sterilization:
        waterConsumedByEquipmentCleaningOnSterilization,
      number_of_cleaning_per_month_on_sterilization:
        numberOfCleaningPerMonthOnSterilization,
      water_consumed_by_equipment_cleaning_on_filling:
        waterConsumedByEquipmentCleaningOnFilling,
      number_of_cleaning_per_month_on_filling:
        numberOfCleaningPerMonthOnFilling,
      water_consumed_by_equipment_cleaning_on_labeling:
        waterConsumedByEquipmentCleaningOnLabeling,
      number_of_cleaning_per_month_on_labeling:
        numberOfCleaningPerMonthOnLabeling,
      water_consumed_by_equipment_cleaning_on_bottling_different_floors:
        waterConsumedByEquipmentCleaningOnBottlingDifferentFloors,
      number_of_cleaning_per_month_on_bottling_different_floors:
        numberOfCleaningPerMonthOnBottlingDifferentFloors,
      ph_high_season_generated_water: phHighSeasonGeneratedWater,
      ph_low_season_generated_water: phLowSeasonGeneratedWater,
      conductivity_high_season_generated_water:
        conductivityHighSeasonGeneratedWater,
      conductivity_low_season_generated_water:
        conductivityLowSeasonGeneratedWater,
      turbidity_high_season_generated_water: turbidityHighSeasonGeneratedWater,
      turbidity_low_season_generated_water: turbidityLowSeasonGeneratedWater,
      CQO_high_season_generated_water: CQOHighSeasonGeneratedWater,
      CQO_low_season_generated_water: CQOLowSeasonGeneratedWater,
      CBO_high_season_generated_water: CBOHighSeasonGeneratedWater,
      CBO_low_season_generated_water: CBOLowSeasonGeneratedWater,
      SST_high_season_generated_water: SSTHighSeasonGeneratedWater,
      SST_low_season_generated_water: SSTLowSeasonGeneratedWater,
      NTK_high_season_generated_water: NTKHighSeasonGeneratedWater,
      NTK_low_season_generated_water: NTKLowSeasonGeneratedWater,
      fenois_high_season_generated_water: fenoisHighSeasonGeneratedWater,
      fenois_low_season_generated_water: fenoisLowSeasonGeneratedWater,
      fosforo_high_season_generated_water: fosforoHighSeasonGeneratedWater,
      fosforo_low_season_generated_water: fosforoLowSeasonGeneratedWater,
      nitratos_high_season_generated_water: nitratosHighSeasonGeneratedWater,
      nitratos_low_season_generated_water: nitratosLowSeasonGeneratedWater,
      sulfatos_high_season_generated_water: sulfatosHighSeasonGeneratedWater,
      sulfatos_low_season_generated_water: sulfatosLowSeasonGeneratedWater,
      ferro_high_season_generated_water: ferroHighSeasonGeneratedWater,
      ferro_low_season_generated_water: ferroLowSeasonGeneratedWater,
      aluminum_high_season_generated_water: aluminumHighSeasonGeneratedWater,
      aluminum_low_season_generated_water: aluminumLowSeasonGeneratedWater,
      cadmio_high_season_generated_water: cadmioHighSeasonGeneratedWater,
      cadmio_low_season_generated_water: cadmioLowSeasonGeneratedWater,
      cobre_high_season_generated_water: cobreHighSeasonGeneratedWater,
      cobre_low_season_generated_water: cobreLowSeasonGeneratedWater,
      cromio_high_season_generated_water: cromioHighSeasonGeneratedWater,
      cromio_low_season_generated_water: cromioLowSeasonGeneratedWater,
      manganes_high_season_generated_water: manganesHighSeasonGeneratedWater,
      manganes_low_season_generated_water: manganesLowSeasonGeneratedWater,
      ph_high_season_treated_water: phHighSeasonTreatedWater,
      ph_low_season_treated_water: phLowSeasonTreatedWater,
      conductivity_high_season_treated_water:
        conductivityHighSeasonTreatedWater,
      conductivity_low_season_treated_water: conductivityLowSeasonTreatedWater,
      turbidity_high_season_treated_water: turbidityHighSeasonTreatedWater,
      turbidity_low_season_treated_water: turbidityLowSeasonTreatedWater,
      CQO_high_season_treated_water: CQOHighSeasonTreatedWater,
      CQO_low_season_treated_water: CQOLowSeasonTreatedWater,
      CBO_high_season_treated_water: CBOHighSeasonTreatedWater,
      CBO_low_season_treated_water: CBOLowSeasonTreatedWater,
      SST_high_season_treated_water: SSTHighSeasonTreatedWater,
      SST_low_season_treated_water: SSTLowSeasonTreatedWater,
      NTK_high_season_treated_water: NTKHighSeasonTreatedWater,
      NTK_low_season_treated_water: NTKLowSeasonTreatedWater,
      fenois_high_season_treated_water: fenoisHighSeasonTreatedWater,
      fenois_low_season_treated_water: fenoisLowSeasonTreatedWater,
      fosforo_high_season_treated_water: fosforoHighSeasonTreatedWater,
      fosforo_low_season_treated_water: fosforoLowSeasonTreatedWater,
      nitratos_high_season_treated_water: nitratosHighSeasonTreatedWater,
      nitratos_low_season_treated_water: nitratosLowSeasonTreatedWater,
      sulfatos_high_season_treated_water: sulfatosHighSeasonTreatedWater,
      sulfatos_low_season_treated_water: sulfatosLowSeasonTreatedWater,
      ferro_high_season_treated_water: ferroHighSeasonTreatedWater,
      ferro_low_season_treated_water: ferroLowSeasonTreatedWater,
      aluminum_high_season_treated_water: aluminumHighSeasonTreatedWater,
      aluminum_low_season_treated_water: aluminumLowSeasonTreatedWater,
      cadmio_high_season_treated_water: cadmioHighSeasonTreatedWater,
      cadmio_low_season_treated_water: cadmioLowSeasonTreatedWater,
      cobre_high_season_treated_water: cobreHighSeasonTreatedWater,
      cobre_low_season_treated_water: cobreLowSeasonTreatedWater,
      cromio_high_season_treated_water: cromioHighSeasonTreatedWater,
      cromio_low_season_treated_water: cromioLowSeasonTreatedWater,
      manganes_high_season_treated_water: manganesHighSeasonTreatedWater,
      manganes_low_season_treated_water: manganesLowSeasonTreatedWater,
    },
    {
      headers: {
        "Content-Type": "application/json",
      },
    }
  );
}
